name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/reusable-validate.yml
    with:
      image_version: ci
      image_tag: ${{ github.ref_name }}
      image_build: ${{ github.sha }}
      run_smoke: true
      release_mode: false
